-- name and updatedAt columns are included in the User table creation in 20260919030000_add_users_and_sessions.
-- This migration is intentionally a no-op to preserve local migration history ordering.
